Repository subaru2003/SpaceWars2, pull requests merged in 2019-06, with the labels that each got.

#148 #147-HPが負の値をとる
  SpaceWars2/functions/Player.cpp
Labels: RANK:A, bug

#146 #132-Ending画面
  SpaceWars2/Main.cpp
  SpaceWars2/Resource.rc
  SpaceWars2/SpaceWars2.vcxproj
  SpaceWars2/SpaceWars2.vcxproj.filters
  SpaceWars2/functions/Debug.cpp
  SpaceWars2/functions/Player.cpp
  SpaceWars2/functions/Player.hpp
  SpaceWars2/images/github-light.png
  SpaceWars2/scenes/Ending.cpp
  SpaceWars2/scenes/Ending.hpp
  SpaceWars2/scenes/Game.cpp
  SpaceWars2/scenes/Game.hpp
  SpaceWars2/scenes/SkillSelect.cpp
  SpaceWars2/scenes/Title.cpp
Labels: RANK:B, enhancement

#149 #133-HPGraphが描画されないことがある
  SpaceWars2/scenes/Game.cpp
Labels: RANK:A, bug

#150 #104-バランス調整ver1.1
  SpaceWars2/functions/MainSkill.cpp
  SpaceWars2/functions/Player.cpp
  SpaceWars2/skills/Flame.cpp
  SpaceWars2/skills/Flame.hpp
Labels: RANK:S, bug

#152 #151-キーボード用操作説明
  SpaceWars2/Main.cpp
  SpaceWars2/Resource.rc
  SpaceWars2/functions/XInput.cpp
  SpaceWars2/images/key-guidance.png
  SpaceWars2/scenes/ControlGuidance.cpp
  SpaceWars2/scenes/ControlGuidance.hpp
Labels: RANK:A, UI, enhancement

#154 #153-Debug用の機能がRelease時に動かないようにする
  SpaceWars2/Main.cpp
  SpaceWars2/functions/Debug.cpp
  SpaceWars2/functions/Debug.hpp
Labels: RANK:A, improvement

#156 #155-Player画像の適用
  SpaceWars2/Main.cpp
  SpaceWars2/Resource.rc
  SpaceWars2/functions/Player.cpp
  SpaceWars2/functions/Player.hpp
  SpaceWars2/images/fire.png
  SpaceWars2/images/l-player.png
  SpaceWars2/images/r-player.png
Labels: RANK:B, enhancement

#158 #157-SkillSelectのReady表示
  SpaceWars2/Resource.rc
  SpaceWars2/images/ready.png
  SpaceWars2/scenes/SkillSelect.cpp
Labels: RANK:B, improvement

#161 #159-効果音を鳴らす
  SpaceWars2/Main.cpp
  SpaceWars2/Resource.rc
  SpaceWars2/functions/Player.cpp
  SpaceWars2/functions/Player.hpp
  SpaceWars2/functions/XInput.cpp
  SpaceWars2/scenes/ControlGuidance.cpp
  SpaceWars2/scenes/Game.cpp
  SpaceWars2/scenes/ScreenGuidance.cpp
  SpaceWars2/scenes/SkillSelect.cpp
  SpaceWars2/scenes/Title.cpp
  SpaceWars2/skills/Bomb.hpp
  SpaceWars2/skills/Flame.hpp
  SpaceWars2/skills/Grenade.cpp
  SpaceWars2/skills/Grenade.hpp
  SpaceWars2/skills/InversionRecovery.cpp
  SpaceWars2/skills/JudgmentTime.hpp
  SpaceWars2/skills/Jump.hpp
  SpaceWars2/skills/Laser.cpp
  SpaceWars2/skills/Laser.hpp
  SpaceWars2/skills/LockOn.hpp
  SpaceWars2/skills/Missile.hpp
  SpaceWars2/skills/Reflection.hpp
  SpaceWars2/skills/Shield.hpp
  SpaceWars2/skills/Shot.hpp
  SpaceWars2/skills/SummonPartner.hpp
  SpaceWars2/sounds/CometHighway.m4a
  SpaceWars2/sounds/IR.mp3
  SpaceWars2/sounds/JT.mp3
  SpaceWars2/sounds/LO.mp3
  SpaceWars2/sounds/SP.mp3
  SpaceWars2/sounds/bomb.mp3
  SpaceWars2/sounds/chargeFull.mp3
  SpaceWars2/sounds/click1.mp3
  SpaceWars2/sounds/click2.mp3
  SpaceWars2/sounds/cursor1.mp3
  SpaceWars2/sounds/flame.mp3
  SpaceWars2/sounds/grenade1.mp3
  SpaceWars2/sounds/grenade2.mp3
  SpaceWars2/sounds/jump.mp3
  SpaceWars2/sounds/laser1.mp3
  SpaceWars2/sounds/laser2.mp3
  SpaceWars2/sounds/missile.mp3
  SpaceWars2/sounds/move1.mp3
  SpaceWars2/sounds/reflection.mp3
  SpaceWars2/sounds/shield.mp3
  SpaceWars2/sounds/shot.mp3
Labels: RANK:B, enhancement

#168 弾や一部スキルに画像適用
  SpaceWars2/Resource.rc
  SpaceWars2/functions/Player.hpp
  SpaceWars2/images/Lockon.png
  SpaceWars2/images/bomb.png
  SpaceWars2/images/clock.png
  SpaceWars2/images/flame.png
  SpaceWars2/images/grenade.png
  SpaceWars2/images/l-playerSP.png
  SpaceWars2/images/missile.png
  SpaceWars2/images/nothing.png
  SpaceWars2/images/r-playerSP.png
  SpaceWars2/scenes/Game.cpp
  SpaceWars2/scenes/SkillSelect.cpp
  SpaceWars2/skills/Bomb.cpp
  SpaceWars2/skills/Flame.cpp
  SpaceWars2/skills/Flame.hpp
  SpaceWars2/skills/Grenade.cpp
  SpaceWars2/skills/LockOn.cpp
  SpaceWars2/skills/Missile.cpp
  SpaceWars2/skills/SummonPartner.cpp
Labels: RANK:C, enhancement

#169 WindowTitle変更
  SpaceWars2/Config.hpp
Labels: RANK:B, improvement

#174 ScreenGuidanceの画像が全滅
  SpaceWars2/scenes/ScreenGuidance.hpp
Labels: RANK:S, bug

#173 #173-操作･画面説明を前に戻すキーを追加
  SpaceWars2/CommonData.cpp
  SpaceWars2/CommonData.hpp
  SpaceWars2/assets/keyboard.png
  SpaceWars2/functions/XInput.cpp
  SpaceWars2/scenes/ControlGuidance.cpp
  SpaceWars2/scenes/ScreenGuidance.cpp
Labels: RANK:B, enhancement

#175 #171-skillSelectのselectingがリセットされない
  SpaceWars2/functions/Player.cpp
  SpaceWars2/functions/Player.hpp
  SpaceWars2/scenes/SkillSelect.cpp
  SpaceWars2/scenes/Title.cpp
Labels: RANK:B, bug

#177 #164-F5･F6･F7 でGame内に移動できるように
  SpaceWars2/Resource.rc
  SpaceWars2/assets/stopwatch-frame.png
  SpaceWars2/functions/Debug.cpp
  SpaceWars2/scenes/ControlGuidance.cpp
  SpaceWars2/scenes/Game.cpp
  SpaceWars2/scenes/Game.hpp
  SpaceWars2/scenes/License.cpp
  SpaceWars2/scenes/ScreenGuidance.cpp
  SpaceWars2/scenes/SkillSelect.cpp
  SpaceWars2/scenes/Title.cpp
Labels: RANK:A, enhancement

#180 #179-Tempertureが100を下回ることがある
  SpaceWars2/functions/Player.cpp
Labels: RANK:C, bug

#189 #181-Missileの追尾範囲を広げたほうがいいかもしれない
  SpaceWars2/SpaceWars2.vcxproj
  SpaceWars2/skills/Missile.hpp
Labels: RANK:C, improvement

#193 #192-IRの調整
  SpaceWars2/skills/InversionRecovery.cpp
  SpaceWars2/skills/InversionRecovery.hpp
Labels: RANK:C, improvement

#199 #197-SPの弾の大きさがおかしい
  SpaceWars2/skills/SummonPartner.cpp
Labels: RANK:B, bug

#195 #194-2回目以降に描画されなかった問題を修正
  SpaceWars2/scenes/SkillSelect.cpp
  SpaceWars2/scenes/SkillSelect.hpp
Labels: RANK:A, bug

#202 #201-Readyを押しがち
  SpaceWars2/functions/Player.cpp
  SpaceWars2/functions/XInput.cpp
  SpaceWars2/scenes/SkillSelect.cpp
Labels: RANK:A, improvement

#206 #196-ジャッジメントタイム中はジャンプが永続
  SpaceWars2/functions/Player.cpp
  SpaceWars2/scenes/Game.cpp
Labels: RANK:C, bug

#205 #204_右プレイヤーのリフレクションの弾の色を明るく
  SpaceWars2/skills/Reflection.cpp
Labels: RANK:A, improvement

#203 #200_IR調整
  SpaceWars2/functions/Player.hpp
  SpaceWars2/skills/InversionRecovery.cpp
  SpaceWars2/skills/InversionRecovery.hpp
Labels: RANK:A, improvement

#209 #208-FullScreen切り替え
  SpaceWars2/Main.cpp
  SpaceWars2/SpaceWars2.vcxproj
  SpaceWars2/SpaceWars2.vcxproj.filters
  SpaceWars2/functions/Utils.cpp
  SpaceWars2/functions/Utils.hpp
Labels: RANK:A, enhancement

#213 #212-Laserが重い
  SpaceWars2/skills/Laser.cpp
  SpaceWars2/skills/Laser.hpp
Labels: RANK:C, bug

#219 #215-ResultのSkillIconにも背景を表示
  SpaceWars2/scenes/Game.cpp
Labels: RANK:A, improvement

#218 #210-ライセンスの山内の名前をkuroameに変更
  SpaceWars2/assets/license.png
Labels: RANK:A, improvement

#220 #217-対応ボタンを増やす
  SpaceWars2/functions/XInput.cpp
Labels: RANK:A, improvement

#221 #207-README･LICENSEをちゃんと書く
  IPA_Font_License_Agreement_v1.0.txt
  LICENSE
  README.md
  SpaceWars2/assets/license.png
  screenshot.png
Labels: RANK:A, improvement
